project_id = "otfgnjgxalsewdwunfrb"

# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
name = "remote-work-deals"

[functions.sitemap]
verify_jwt = false