// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otfgnjgxalsewdwunfrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Zmduamd4YWxzZXdkd3VuZnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjQ1MzUsImV4cCI6MjA2NTI0MDUzNX0.XWoZgz4f4w_1m-PqSjRoDz8e7Rz5yPOUopJpdX4e3ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);